NDefines.NMilitary.BASE_NIGHT_ATTACK_PENALTY = 0 -- -0.5
NDefines.NAir.DETECT_CHANCE_FROM_NIGHT = 0 -- -0.2
NDefines.NAir.DAY_NIGHT_COVERAGE_FACTOR = 0 -- 0.5
NDefines.NAir.CAS_NIGHT_ATTACK_FACTOR = 0 -- 0.1